var tableauQuestion = [
    {   question : "Ao entrar na cidade, área residencial ou comercial, acima de 100km/h, o que você deve fazer?",
        propositionA : "Acelerar e chegar a 120km/h",
        propositionB : "Manter a velocidade caso não esteja ultrapassando outros veículos",
        propositionC : "Reduzir para 80km/h",
        propositionD : "Manter a velocidade de 100km/h.",
        reponse : "C"},

    {   question : "Se você está passando uma sinaleira e vê um pedestre atravessando, o que você faz?",
        propositionA : "Você passa pelo pedestre",
        propositionB : "Xinga o pedestre",
        propositionC : "Você aguarda o pedestre atravessar",
        propositionD : "Você atira no pedestre e vaza",
        reponse : "C"},

    {   question : "Quando não houver nenhuma indicação, a velocidade máxima permitida em uma área residencial é de: __ km/h",
        propositionA : "60",
        propositionB : "80",
        propositionC : "40",
        propositionD : "120",
        reponse : "A"},

  {   question : "Antes de trocar de pista você deve:",
        propositionA : "Checar os espelhos",
        propositionB : "Checar os pontos cegos",
        propositionC : "Sinalizar suas intenções",
        propositionD : "Todas as anteriores",
        reponse : "D"},

  {   question : "Ao não precisar mais utilizar seu veículo, você deve:",
        propositionA : "Deixa-lo em qualquer lugar, outra hora você pega",
        propositionB : "Coloca-lo em estacionamento público ou garagem privada",
        propositionC : "Explodi-lo",
        propositionD : "Qualquer lugar é lugar",
        reponse : "B"},

  {   question : "Você pode atravessar uma sinaleira quando:",
        propositionA : "Ela está vermelha",
        propositionB : "Quando não há ninguém no cruzamento",
        propositionC : "Você está em uma zona escolar",
        propositionD : "Quando ela está verde",
        reponse : "D"},

  {   question : "Um pedestre tem o sinal para não atravessar, o que você faz?",
        propositionA : "Deixa ele passar",
        propositionB : "Você observa e simplesmente continua",
        propositionC : "Você acena e diz para ele passar",
        propositionD : "Você continua pois o sinal para você é verde",
        reponse : "D"},

  {   question : "O que é permitido na hora de executar uma ultrapassagem?",
        propositionA : "Ficar colado no veículo da frente para ultrapassa-lo mais rápido",
        propositionB : "Ultrapassar sem sair da estrada",
        propositionC : "Pegar a direção contrária da via para ultrapassar",
        propositionD : "Exceder o limite de velocidade para a ultrapassar",
        reponse : "C"},

  {   question : "Você está dirigindo em uma rodovia que indica que a velocidade máxima é de 120km/h. Sua velocidade mínimina indicada é de:",
        propositionA : "110km/h",
        propositionB : "80km/h",
        propositionC : "20km/h",
        propositionD : "50km/h",
        reponse : "A"},

  {   question : "Quando você é ultrapassado por um veículo é importante você NÃO:",
        propositionA : "Reduzir a velocidade",
        propositionB : "Checar seus espelhos",
        propositionC : "Olhar os outros motoristas",
        propositionD : "Aumentar sua velocidade",
        reponse : "D"},
]
